# select_color_node: select set of nodes or edge with different color
# drag_node: possibility to drag the node
# remove_edge: delete a selected edge
# remove_node: delete a selected node
# add_node: add a node
# add_edge: add an edge
# add_edge_dir: add a directed edge
# choice: possibility to chioice between yes or no 
# edit_label: label on edge or node are editable
# none: no tools and no interactivity
# all: all tools are created
# reset: reset data structure and draw the initial graph TODO
# submit: submit solution

exe_1:
  text:
    - 'exercise_graph/data/texts/intro_1.md'
    - 'exercise_graph/data/texts/problem_1.md'
  graph: 'exercise_graph/data/graph_model/graph_rizzi.graphml'
  # none if there isn't data extra
  dataextra: 'none'
  tools:
    - select_color_node 
    - drag_node
    - choice
    - save

exe_2:
  text:
    - 'exercise_graph/data/texts/intro_2.md'
    - 'exercise_graph/data/texts/problem_2.md'
  graph: 'exercise_graph/data/graph_model/graph_rizzi.graphml'
  # none if there isn't data extra
  dataextra: 'none'
  tools:
    - select_color_node 
    - drag_node
    - choice
    - save

exe_3:
  text:
    - 'exercise_graph/data/texts/intro_3.md'
    - 'exercise_graph/data/texts/problem_3.md'
  graph: 'exercise_graph/data/graph_model/graph_rizzi.graphml'
  # none if there isn't data extra
  dataextra: 'none'
  tools:
    - select_color_node
    - drag_node
    - remove_edge
    - save

exe_4:
  text:
    - 'exercise_graph/data/texts/intro_4.md'
    - 'exercise_graph/data/texts/problem_4.md'
  graph: 'exercise_graph/data/graph_model/graph_rizzi.graphml'
  # none if there isn't data extra
  dataextra: 'none'
  tools:
    - select_color_node 
    - drag_node 
    - remove_edge
    - save

exe_5:
  text:
    - 'exercise_graph/data/texts/intro_5.md'
    - 'exercise_graph/data/texts/problem_5.md'
    - 'exercise_graph/data/texts/sub_problem_5_1.md'
    - 'exercise_graph/data/texts/sub_problem_5_2.md'
  graph: 'exercise_graph/data/graph_model/graph_rizzi.graphml'
  # none if there isn't data extra
  dataextra: 'exercise_graph/data/sub_problem/sub_prob.yaml'
  tools:
    - select_color_node 
    - drag_node 
    - save

exe_6:
  text:
    - 'exercise_graph/data/texts/intro_6.md'
    - 'exercise_graph/data/texts/problem_6.md'
    - 'exercise_graph/data/texts/sub_problem_6_1.md'
  graph: 'exercise_graph/data/graph_model/graph_rizzi.graphml'
  # none if there isn't data extra
  dataextra: 'exercise_graph/data/sub_problem/sub_prob.yaml'
  tools:
    - select_color_node
    - drag_node
    - edit_label
    - save

exe_7:
  text:
    - 'exercise_graph/data/texts/intro_7.md'
    - 'exercise_graph/data/texts/problem_7.md'
  graph: 'exercise_graph/data/graph_model/graph_rizzi.graphml'
  # none if there isn't data extra
  dataextra: 'exercise_graph/data/sub_problem/sub_prob.yaml'
  tools:
    - select_color_node
    - drag_node
    - edit_label
    - save
    
js_file: '../lib/sigmajs/sigma-graph.js'
